#!/bin/bash
# description: Script to wake up Agent.js from Popbox module
# chkconfig: 2345 85 15
#########################################
##Autor:        Carlos Enrique Gómez Gómez
##Depar:        Release Engineering & Management
#########################################
## Values
# processname: popbox
# config: /opt/popbox/src/config.js
# pidfile: /var/run/popbox.pid

source /etc/rc.d/init.d/functions

NAME=popbox
SOURCE_DIR=/opt/pdi-popbox/bin
SOURCE_FILE=popbox
 
user=popbox
pidfile=/var/run/pdi-popbox/$NAME.pid
logfile=/var/log/pdi-popbox/$NAME.log
forever_dir=/var/run/forever
 
node=node
sed=sed
home_dir="/opt/pdi-popbox"
forever=$home_dir/node_modules/forever/bin/forever 
 
start() {
  echo "Starting $NAME node instance: "
 
  if [ "$foreverid" == "" ]; then
    # Create the log and pid files, making sure that
    # the target use has access to them
    mkdir -p $(dirname $logfile)
    touch $logfile
    chown -R $user $(dirname $logfile)
    mkdir -p $(dirname $pidfile)
    touch $pidfile
    chown $user $(dirname $pidfile)
 
    # Launch the application
    cd $home_dir
    daemon --user=$user \
      $forever start -p $forever_dir --pidFile $pidfile -l $logfile -a \
      $SOURCE_DIR/$SOURCE_FILE
    RETVAL=$?
    cd -
  else
    echo "Instance already running"
    RETVAL=0
  fi
}
 
stop() {
  echo -n "Shutting down $NAME node instance : "
  if [ "$foreverid" != "" ]; then
    #$node $SOURCE_DIR/prepareForStop.js
    echo HHH $forever stop -p $forever_dir $pid
    $forever stop -p $forever_dir $pid
  else
    echo "Instance is not running";
  fi
  RETVAL=$?
}
 
if [ -f $pidfile ]; then
  read pid < $pidfile
else
  pid=""
fi
echo HHHH pid $pid
if [ "$pid" != "" ]; then
  # Gnarly sed usage to obtain the foreverid.
  sed1="/$pid\]/p"
  sed2="s/.*\[\([0-9]\+\)\].*\s$pid\].*/\1/g"
  echo  "foreverid=$forever list -p $forever_dir | $sed -n $sed1 | $sed $sed2"


  foreverid=`$forever list -p $forever_dir | $sed -n $sed1 | $sed $sed2`
else
  foreverid=""
fi
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile}
    ;;
  *)
    echo "Usage:  {start|stop|status}"
    exit 1
    ;;
esac
exit $RETVAL