#!/bin/bash
# description: Script to wake up Agent.js from Popbox module
# chkconfig: 2345 85 15
#########################################
##Autor:        Carlos Enrique Gómez Gómez
##Depar:        Release Engineering & Management
#########################################
## Values
# processname: node popbox
# config: /opt/popbox/src/config.js
# pidfile: /var/run/pdi-popbox/popbox.pid

source /etc/rc.d/init.d/functions

RETVAL=0
prog="popbox"
home_dir="/opt/pdi-popbox"
pidfile=/var/run/pdi-popbox/popbox.pid

start() {
  echo -n $"Starting $prog: "
  daemon --user $prog --pidfile $pidfile $home_dir/bin/$prog
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
  return $RETVAL
}

stop() {
    PID=`cat $pidfile 2>/dev/null`
    if [ -n "$PID" ]; then
        echo -n $"Shutting down $prog: "
        kill -9 $PID
        echo_success
        RETVAL=0
    else
        echo -n $"$prog is not running"
        echo_failure
        RETVAL=1
    fi

    echo
    return $RETVAL
}

restart() {
  stop
  start
}

condrestart() {
    [-e /var/lock/subsys/$prog] && restart || :
}

case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  status)
  status -p $pidfile $prog
  RETVAL=$?
  ;;
  restart)
  restart
  ;;
  condrestart|try-restart)
  condrestart
  ;;
   *)
  echo $"Usage: $0 {start|stop|status|restart|condrestart}"
  RETVAL=1
esac

exit $RETVAL

